/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CourseDto } from '../../models/course-dto';

export interface AddCourse$Plain$Params {
      body?: CourseDto
}

export function addCourse$Plain(http: HttpClient, rootUrl: string, params?: AddCourse$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CourseDto>> {
  const rb = new RequestBuilder(rootUrl, addCourse$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CourseDto>;
    })
  );
}

addCourse$Plain.PATH = '/api/Courses';
