/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CourseDto } from '../../models/course-dto';

export interface GetCourses$Json$Params {
}

export function getCourses$Json(http: HttpClient, rootUrl: string, params?: GetCourses$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CourseDto>>> {
  const rb = new RequestBuilder(rootUrl, getCourses$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CourseDto>>;
    })
  );
}

getCourses$Json.PATH = '/api/Courses';
