/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourseDto {
  description?: string | null;
  id?: number;
  name?: string | null;
  startDate?: string;
}
