/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CourseDto } from '../models/course-dto';
export interface SubscriptionDto {
  course?: CourseDto;
  id?: number;
  trackedHours?: number;
}
