/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EUserType } from '../models/e-user-type';
export interface UserDto {
  id?: number;
  userType?: EUserType;
  username?: string | null;
}
